# -*- coding: utf-8 -*-

{
    'name': 'Wilco - Project Management',
    'version': '1.0.0',
    'category': 'Wilco',
    'author': 'Stan Ng',
    'sequence': -100,
    'summary': 'Wilco Project Management',
    'description': """
This module contains all the common features of Wilco Project Management
    """,
    'depends': ['base','web','sale','sale_management','project','purchase','account','om_account_budget','accounting_pdf_reports','analytic'],
    'data': [
        'data/ir_cron_data.xml',
        'views/res_partner_views_inherit.xml',
        'wizard/wilco_project_status_report_wizard_views.xml',
        'views/project_views_inherit.xml',
        'views/project_status_listing_view.xml',
        'views/sale_order_views_inherit.xml',
        'views/purchase_views_inherit.xml',
        'views/account_analytic_account_views_inherit.xml',
        'views/analytic_line_views_inherit.xml',
        'views/account_move_views_inherit.xml',
        'views/account_payment_views_inherit.xml',
        'views/analytic_account_views_inherit.xml',
        'views/analytic_line_views_inherit.xml',
        'views/product_views_inherit.xml',
        'views/res_company_views_inherit.xml',
        'views/res_config_settings_views_inherit.xml',
        'views/webclient_templates_inherit.xml',
        'views/wilco_customer_invoice_items_views.xml',
        'views/wilco_vendor_bill_items_views.xml',
        'report/paperformat_data.xml',
        'report/sale_report_template.xml',
        'report/sale_report_inherit.xml',
        'report/sale_report_views.xml',
        'report/purchase_report_template.xml',
        'report/purchase_report_inherit.xml',
        'report/purchase_report_views.xml',
        'report/invoice_report_inherit.xml',
        'report/payment_receipt_report_inherit.xml',
        'report/journal_entries_report_inherit.xml',
        'report/signature_template.xml',
        'report/document_reference_template.xml',
        'report/report_template_inherit.xml',
        'wizard/account_payment_register_views_inherit.xml',
        'wizard/sale_make_invoice_advance_views_inherit.xml',
        'report/report_aged_analytic_template.xml',
        'report/report_views.xml',
        'wizard/aged_analytic_view.xml',
        'views/wilco_customer_invoice_summary_views.xml',
        'wizard/wilco_invoice_summary_wizard_views.xml',
        'views/wilco_vendor_bill_summary_views.xml',
        'wizard/wilco_vendor_bill_summary_wizard_views.xml',
        'report/project_status_report_views.xml',
        'report/project_status_report_template.xml',
        'report/project_status_listing_report_views.xml',
        'report/project_status_listing_report_template.xml',
        'security/ir.model.access.csv',
    ],
    'demo': [],
    'application': True,
    'auto_install': False,
    'assets': {},
    'license': 'LGPL-3',
}
